import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';

export default function Terms() {
  const navigate = useNavigate();

  const containerStyle: React.CSSProperties = {
    minHeight: '100vh',
    backgroundColor: '#0d1117',
    fontFamily: "'Inter', sans-serif",
    color: '#e6edf3',
  };
  const headerStyle: React.CSSProperties = {
    position: 'sticky', top: 0, zIndex: 50,
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '14px 24px',
    backgroundColor: 'rgba(13,17,23,0.88)',
    backdropFilter: 'blur(16px)',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
  };
  const h2Style: React.CSSProperties = {
    fontFamily: "'Anton', sans-serif", fontSize: 22, color: 'white',
    letterSpacing: '0.02em', textTransform: 'uppercase', marginBottom: 14, marginTop: 32,
  };
  const pStyle: React.CSSProperties = {
    color: '#c9d1d9', fontSize: 13.5, lineHeight: 1.75, marginBottom: 12,
  };
  const liStyle: React.CSSProperties = {
    color: '#c9d1d9', fontSize: 13.5, lineHeight: 1.75, marginBottom: 6, paddingLeft: 8,
  };

  return (
    <div style={containerStyle}>
      <header style={headerStyle}>
        <button
          onClick={() => navigate(-1)}
          style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.08)', color: '#e6edf3', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
        >
          <ArrowLeft size={14} /> Back
        </button>
        <button onClick={() => navigate('/')} style={{ fontFamily: "'Anton', sans-serif", fontSize: 22, color: 'white', letterSpacing: '0.04em', textTransform: 'uppercase', background: 'none', border: 'none', cursor: 'pointer' }}>InterviewAI</button>
        <div style={{ width: 80 }} />
      </header>

      <main style={{ maxWidth: 680, margin: '0 auto', padding: '32px 24px 60px' }}>
        {/* Title */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(244,132,95,0.1)' }}>
            <FileText size={18} style={{ color: '#F4845F' }} />
          </div>
          <h1 style={{ fontFamily: "'Anton', sans-serif", fontSize: 'clamp(28px, 5vw, 40px)', color: 'white', letterSpacing: '-0.01em', textTransform: 'uppercase' }}>
            Terms of Service
          </h1>
        </div>
        <p style={{ color: '#8b949e', fontSize: 12, marginBottom: 32 }}>Last updated: June 2, 2026</p>

        <p style={pStyle}>
          Welcome to InterviewAI. By accessing or using this Service, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please do not use the Service.
        </p>

        <h2 style={h2Style}>1. Description of Service</h2>
        <p style={pStyle}>
          InterviewAI is a web-based application that provides AI-powered mock interviews. Users upload their resume, select an interview mode, answer AI-generated questions via text or voice, and receive performance analytics and improvement suggestions.
        </p>

        <h2 style={h2Style}>2. Account & Authentication</h2>
        <p style={pStyle}>
          You must sign in with a valid Google account to use the Service. You are responsible for maintaining the security of your account. You agree to provide accurate information and not to impersonate any other person.
        </p>

        <h2 style={h2Style}>3. Acceptable Use</h2>
        <p style={pStyle}>You agree not to:</p>
        <ul style={{ listStyle: 'none', padding: 0 }}>
          <li style={liStyle}>• Upload content that is illegal, offensive, or violates the rights of others.</li>
          <li style={liStyle}>• Upload someone else's resume without their explicit consent.</li>
          <li style={liStyle}>• Attempt to reverse-engineer, exploit, or abuse the AI system or API.</li>
          <li style={liStyle}>• Use automated scripts, bots, or scrapers to access the Service.</li>
          <li style={liStyle}>• Circumvent any rate limits or security measures.</li>
        </ul>

        <h2 style={h2Style}>4. AI-Generated Content</h2>
        <p style={pStyle}>
          The interview questions, evaluations, feedback, and roadmaps generated by InterviewAI are produced by artificial intelligence (Groq API). This content is provided for practice and educational purposes only. We make no guarantees about the accuracy, completeness, or suitability of AI-generated responses. AI evaluations should not be treated as professional career advice.
        </p>

        <h2 style={h2Style}>5. Intellectual Property</h2>
        <p style={pStyle}>
          You retain all rights to your resume content. By uploading your resume, you grant us a limited, non-exclusive license to process it solely for the purpose of generating interview content. We do not claim ownership of your uploaded data.
        </p>

        <h2 style={h2Style}>6. Limitation of Liability</h2>
        <p style={pStyle}>
          InterviewAI is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to: loss of data, inaccurate AI evaluations, or service interruptions. Your use of the Service is at your own risk.
        </p>

        <h2 style={h2Style}>7. Service Availability</h2>
        <p style={pStyle}>
          We reserve the right to modify, suspend, or discontinue the Service at any time without prior notice. We do not guarantee uninterrupted access to the Service.
        </p>

        <h2 style={h2Style}>8. Termination</h2>
        <p style={pStyle}>
          We may terminate or suspend your access to the Service at any time, without prior notice, if you violate these Terms. Upon termination, your right to use the Service ceases immediately.
        </p>

        <h2 style={h2Style}>9. Changes to Terms</h2>
        <p style={pStyle}>
          We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms.
        </p>

        <h2 style={h2Style}>10. Contact</h2>
        <p style={pStyle}>
          For questions about these Terms, please contact us at:{' '}
          <a href="mailto:gautamdas@interviewai.app" style={{ color: '#F4845F', textDecoration: 'none' }}>gautamdas@interviewai.app</a>
        </p>
      </main>
    </div>
  );
}
